//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBike
    {
        public int BikeId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Engine { get; set; }
        public Nullable<int> wheels { get; set; }
        public string bikeType { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
    
        public virtual tblVehicleType tblVehicleType { get; set; }
    }
}
